//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class LoanInformation
{
    public virtual int LoanID
    {
        get;
        set;
    }

    public virtual string AdminComment
    {
        get;
        set;
    }

    public virtual string UserComment
    {
        get;
        set;
    }

    public virtual DateTime LoanDate
    {
        get;
        set;
    }

    public virtual DateTime ReturnDate
    {
        get;
        set;
    }

    public virtual int Component
    {
        get;
        set;
    }

    public virtual string IsEmailSend
    {
        get;
        set;
    }

}

