//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Text;

public class LoanInformation
{
	public virtual int LoanID
	{
		get;
		set;
	}

	public virtual SqlDateTime? LoanDate
	{
		get;
		set;
	}

	public virtual SqlDateTime? ReturnDate
	{
		get;
		set;
	}

	public virtual int Component
	{
		get;
		set;
	}

	public virtual string IsEmailSend
	{
		get;
		set;
	}

	public virtual SqlDateTime? ReservationDate
	{
		get;
		set;
	}

	public virtual string MobilNr
	{
		get;
		set;
	}

	public virtual string OwnerID
	{
		get;
		set;
	}

	public virtual string ReservationID
	{
		get;
		set;
	}

}

