//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Controls;
using System.Windows.Media.Imaging;
using SimpleMvvmToolkit;

namespace PCApplikationMVVM
{
    public class Component: ModelBase<Component>
    {
        private int _componetID;
        public int ComponentID
        {
            get { return _componetID; }
            set
            {
                _componetID = value;
                NotifyPropertyChanged(m => m.ComponentID);
            }
        }

        private string _componentName;
        public string ComponentName
        {
            get { return _componentName; }
            set
            {
                _componentName = value;
                NotifyPropertyChanged(m => m.ComponentName);
            }
        }

        private string _category;
        public string Category
        {
            get { return _category; }
            set
            {
                _category = value;
                NotifyPropertyChanged(m => m.Category);
            }
        }
       
        private string datasheet_;
        public string Datasheet
        {
            get { return datasheet_; }
            set
            {
                datasheet_ = value;
                NotifyPropertyChanged(m => m.Datasheet);
            }
        }

        

        private int _componentNumber;
        public int ComponentNumber
        {
            get { return _componentNumber; }
            set
            {
                _componentNumber = value;
                NotifyPropertyChanged(m => m.ComponentNumber);
            }
        }

        private string _image;
        public string Image
        {
	        get { return _image; }
            set
            {
                _image = value;
                NotifyPropertyChanged(m => m.Image);
            }
        }

        private LoanInformation actualLoanInformation_;
        public LoanInformation ActualLoanInformation
        {
            get { return actualLoanInformation_; }
            set
            {
                actualLoanInformation_ = value;
                NotifyPropertyChanged(m => m.ActualLoanInformation);
            }
        }

        private string adminComment_;
        public string AdminComment
        {
            get { return adminComment_; }
            set
            {
                adminComment_ = value;
                NotifyPropertyChanged(m => m.AdminComment);
            }
        }


        private string userComment_;
        public string UserComment
        {
            get { return userComment_; }
            set
            {
                userComment_ = value;
                NotifyPropertyChanged(m => m.UserComment);
            }
        }

        private string _componetInfo;
        public string ComponentInfo
        {
            get { return _componetInfo; }
            set
            {
                _componetInfo = value;
                NotifyPropertyChanged(m => m.ComponentInfo);
            }
        }

        private string _serieNr;
        public string SerieNr
        {
            get { return _serieNr; }
            set
            {
                _serieNr = value;
                NotifyPropertyChanged(m => m.SerieNr);
            }
        }

        private int _amountLoaned;
        public int AmountLoaned
        {
            get { return _amountLoaned; }
            set
            {
                _amountLoaned = value;
                NotifyPropertyChanged(m => m.AmountLoaned);
            }
        }
        private int _amountComponets;
        public int AmountComponets
        {
            get { return _amountComponets; }
            set
            {
                _amountComponets = value;
                NotifyPropertyChanged(m => m.AmountComponets);
            }
        }

        private string _manufacturerLink;
        public string ManufacturerLink
        {
            get { return _manufacturerLink; }
            set
            {
                _manufacturerLink = value;
                NotifyPropertyChanged(m => m.ManufacturerLink);
            }
        }
        public Component()
        {
            actualLoanInformation_ = new LoanInformation();
        }

		//Returns an image from an online URL, this should belong in MainViewModel but to accommodate databinding issues it's placed here
		public string RenderImage
		{
			get
			{

				if (!string.IsNullOrEmpty(Image))
					return Image;
				else
				{
					var path = System.IO.Directory.GetCurrentDirectory();
					path = System.IO.Directory.GetParent(path).ToString();
					path = System.IO.Directory.GetParent(path).ToString();

					return path + "\\noimage.png";
				}
			}
			set
			{

			}
		}

        //Copy Constructor
        public Component(Component copyComponent)
        {
            actualLoanInformation_ = new LoanInformation();

            ComponentID = copyComponent.ComponentID;
            ComponentName = copyComponent.ComponentName;
            Category = copyComponent.Category;
            Datasheet = copyComponent.Datasheet;
            UserComment = copyComponent.UserComment;
            AdminComment = copyComponent.AdminComment;
            ComponentNumber = copyComponent.ComponentNumber;
            Image = copyComponent.Image;
            ComponentInfo = copyComponent.ComponentInfo;
            SerieNr = copyComponent.SerieNr;
            ManufacturerLink = copyComponent.ManufacturerLink;

            ActualLoanInformation.LoanID = copyComponent.ActualLoanInformation.LoanID;
            ActualLoanInformation.LoanDate = copyComponent.ActualLoanInformation.LoanDate;
            ActualLoanInformation.OwnerID = copyComponent.ActualLoanInformation.OwnerID;
            ActualLoanInformation.ReservationID = copyComponent.ActualLoanInformation.ReservationID;
            ActualLoanInformation.ReturnDate = copyComponent.ActualLoanInformation.ReturnDate;
            ActualLoanInformation.Component = copyComponent.ActualLoanInformation.Component;
            ActualLoanInformation.IsEmailSend = copyComponent.ActualLoanInformation.IsEmailSend;
            ActualLoanInformation.ReservationDate = copyComponent.ActualLoanInformation.ReservationDate;
            ActualLoanInformation.MobilNr = copyComponent.ActualLoanInformation.MobilNr;
        }

        public void SetProperties(Component copyComponent)
        {
            ComponentID = copyComponent.ComponentID;
            ComponentName = copyComponent.ComponentName;
            Category = copyComponent.Category;
            Datasheet = copyComponent.Datasheet;
            UserComment = copyComponent.UserComment;
            AdminComment = copyComponent.AdminComment;
            ComponentNumber = copyComponent.ComponentNumber;
            Image = copyComponent.Image;
            ComponentInfo = copyComponent.ComponentInfo;
            SerieNr = copyComponent.SerieNr;
            ManufacturerLink = copyComponent.ManufacturerLink;

            ActualLoanInformation.LoanID = copyComponent.ActualLoanInformation.LoanID;
            ActualLoanInformation.LoanDate = copyComponent.ActualLoanInformation.LoanDate;
            ActualLoanInformation.OwnerID = copyComponent.ActualLoanInformation.OwnerID;
            ActualLoanInformation.ReservationID = copyComponent.ActualLoanInformation.ReservationID;
            ActualLoanInformation.ReturnDate = copyComponent.ActualLoanInformation.ReturnDate;
            ActualLoanInformation.Component = copyComponent.ActualLoanInformation.Component;
            ActualLoanInformation.IsEmailSend = copyComponent.ActualLoanInformation.IsEmailSend;
            ActualLoanInformation.ReservationDate = copyComponent.ActualLoanInformation.ReservationDate;
            ActualLoanInformation.MobilNr = copyComponent.ActualLoanInformation.MobilNr;
        }
    }
}