//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Globalization;
using System.Linq;
using System.Text;
using PCApplikation;
using SimpleMvvmToolkit;

public class LoanInformation : ModelBase<LoanInformation>
{
    private string yearFirst_ = "yyyy-MM-dd";

	private int loanID_;
    public int LoanID
    {
        get { return loanID_; }
        set
        {
            loanID_ = value;
            NotifyPropertyChanged(m => m.LoanID);
        }
    }

    private string _ownerID;
    public string OwnerID
    {
        get { return _ownerID; }
        set
        {
            _ownerID = value;
            NotifyPropertyChanged(m => m.OwnerID);
        }
    }

    private string reservationId;
    public string ReservationID
    {
        get { return reservationId; }
        set
        {
            reservationId = value;
            NotifyPropertyChanged(m => m.ReservationID);
        }
    }

    private SqlDateTime? loanDate_;
	public SqlDateTime? LoanDate
    {
        get { return loanDate_; }
        set
        {
            loanDate_ = value;
            NotifyPropertyChanged(m => m.LoanDate);
			NotifyPropertyChanged(m => m.LoanDateString);
        }
    }

	public string LoanDateString
	{
		get
		{
			try
			{
			    if (LoanDate.HasValue)
                    return LoanDate.Value.Value.ToShortDateString();
			    else
			        return "";
			}
			catch (Exception)
			{
				return "";
			}
		}
		set { LoanDate = DateTime.Parse(value, CultureInfo.CreateSpecificCulture("da-DK")); }
	}

    private SqlDateTime? reservationDate_;
    public SqlDateTime? ReservationDate
    {
        get { return reservationDate_; }
        set
        {
            reservationDate_ = value;
            NotifyPropertyChanged(m => m.ReservationDate);
			NotifyPropertyChanged(m => m.ReservationDateString);
        }
    }

	public string ReservationDateString
	{
		get
		{
			try
			{
			    if (ReservationDate.HasValue)
			        return ReservationDate.Value.Value.ToShortDateString();
			    else
			        return "";
			}
			catch (Exception)
			{
				return "";
			}
		}
		set { ReservationDate = DateTime.Parse(value, CultureInfo.CreateSpecificCulture("da-DK")); }
	}

	private SqlDateTime? returnDate_;
	public SqlDateTime? ReturnDate
    {
        get { return returnDate_; }
        set
        {
            returnDate_ = value;
            NotifyPropertyChanged(m => m.ReturnDate);
			NotifyPropertyChanged(m => m.ReturnDateString);
            NotifyPropertyChanged(m => m.ReturnDateStringYearFirst);
        }
    }

	public string ReturnDateString
	{
		get
		{
			try
			{
			    if (ReturnDate.HasValue)
			        return ReturnDate.Value.Value.ToShortDateString();
			    else
			        return "";
			}
			catch (Exception)
			{
				return "";
			}
		}
		set { ReturnDate = DateTime.Parse(value, CultureInfo.CreateSpecificCulture("da-DK")); }
	}

    public string ReturnDateStringYearFirst
    {
        get
        {
            try
            {
                if (ReturnDate.HasValue)
                    return ReturnDate.Value.Value.ToString(yearFirst_);
                else
                    return "";
            }
            catch (Exception)
            {
                return "";
            }
        }
        set { ReturnDate = DateTime.Parse(value, CultureInfo.CreateSpecificCulture("da-DK")); }
    }

    private int component_;
    public int Component
    {
        get { return component_; }
        set
        {
            component_ = value;
            NotifyPropertyChanged(m => m.Component);
        }
    }

    private string isEmailSend_;
    public string IsEmailSend
    {
        get { return isEmailSend_; }
        set
        {
            isEmailSend_ = value;
            NotifyPropertyChanged(m => m.IsEmailSend);
        }
    }

    public LoanInformation()
    {
        LoanDate = new SqlDateTime();
		ReturnDate = new SqlDateTime();
    }

    private string mobilNr_;
    public string MobilNr
    {
        get { return mobilNr_; }
        set
        {
            mobilNr_ = value;
			NotifyPropertyChanged(m => m.MobilNr);
        }
    }

    public LoanInformation(LoanInformation LIF)
    {
		LoanDate = new SqlDateTime();
		ReturnDate = new SqlDateTime();

        OwnerID = LIF.OwnerID;
        ReservationID = LIF.ReservationID;
        LoanID = LIF.LoanID;
        LoanDate = LIF.LoanDate;
        ReturnDate = LIF.ReturnDate;
        Component = LIF.Component;
        IsEmailSend = LIF.IsEmailSend;
        MobilNr = LIF.MobilNr;
        ReservationDate = LIF.ReservationDate;
    }
}