//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Controls;

namespace PCApplikation
{
    public class Component
    {
        public virtual int ComponentID { get; set; }

        public virtual string Tags { get; set; }

        public virtual string Name { get; set; }

        public virtual string Category { get; set; }

        public virtual string Datasheet { get; set; }

        public virtual int OwnerID { get; set; }

        public virtual int ComponentNumber { get; set; }

        public virtual string Image { get; set; }

        public virtual int LoanInformation { get; set; }

        public virtual string ComponentInfo { get; set; }

        public Component()
        {

        }
    }
}

