//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Web.Models
{
    public class Component
    {
        public virtual int ComponentID
        {
            get;
            set;
        }

        public virtual string ComponentName
        {
            get;
            set;
        }

        public virtual string Category
        {
            get;
            set;
        }

        public virtual string Datasheet
        {
            get;
            set;
        }

        public virtual int ComponentNumber
        {
            get;
            set;
        }

        public virtual string Image
        {
            get;
            set;
        }

        public virtual string ComponentInfo
        {
            get;
            set;
        }

        public virtual string SerieNr
        {
            get;
            set;
        }

        public virtual string UserComment
        {
            get;
            set;
        }

        public virtual string AdminComment
        {
            get;
            set;
        }

        public virtual string ManufacturerLink
        {
            get;
            set;
        }

        public virtual LoanInformation Fra
        {
            get;
            set;
        }

    }


}
